tasks:
  - name: aws-cli
    env :
      AWS_CLI_AUTO_PROMPT: on-partial
    before : |
      cd /workspaces
      curl "https://awscli.amazonaws.com/aawscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip "awscliv2.zip"
      sudo ./aws/install
    